name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node: [16,18,20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
       
      - name: Node.js | ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install
      - run: npm run test

      - name: Build Docker Image
        run: docker build -t docker-ci-api: latest .