name: CI

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Install dependencies
      #   run: npm install

      # - name: Run tests
      #   run: npm test

      # - name: Build
      #   run: npm run build

      # - name: Deploy
      #   run: |
      #     echo "Deploying to production..."
      #     # Add your deployment script here