name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node: [16,18,20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
       
      - name: Node.js | ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install
      - run: npm run test

      - name: Generate Tag
        id: generate_tag
        run: |
         SHA=$(echo $GITHUB_SHA | head -c7)
         echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        run: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: docker build -t pedro4r/docker-ci-api:${{ steps.generate_tag.outputs.sha }} .

      - name: Push image
        run: docker push pedro4r/docker-ci-api:${{ steps.generate_tag.outputs.sha }}